import type { InputState } from './types'

export const defaultInput: InputState = {
  general: {
    modelWeight: 800,
    modelWeightUnit: 'g',
    weightMode: 'inclDrive',
    rotors: 4,
    rotorLayout: 'flat',
    frameSizeMm: 450,
    fcuTiltLimitDeg: 60,
    noTiltLimit: false,
    elevation: 0,
    elevationUnit: 'm',
    airTemp: 25,
    airTempUnit: 'c',
    pressure: 1013.25,
    pressureUnit: 'hPa',
  },
  battery: {
    cellType: 'LiPo',
    chargeState: 'full',
    seriesCells: 4,
    parallelCells: 1,
    cellCapacityMah: 5000,
    maxDischargeC: 50,
    internalResistanceMOhm: 5,
    nominalVoltage: 3.7,
    fullChargeVoltage: 4.2,
    cellWeightG: 100,
  },
  esc: {
    escType: 'Custom',
    continuousCurrentA: 40,
    burstCurrentA: 55,
    internalResistanceMOhm: 2,
    weightG: 30,
  },
  accessories: {
    currentDrainA: 1.5,
    weightG: 80,
  },
  motor: {
    manufacturerModel: 'Custom',
    kv: 920,
    noLoadCurrentA: 0.5,
    noLoadVoltage: 10,
    currentLimitA: 30,
    powerLimitW: 500,
    statorResistanceMOhm: 72,
    caseLengthMm: 26,
    poles: 14,
    weightG: 110,
  },
  propeller: {
    propType: 'Custom',
    yokeTwistDeg: 0,
    diameter: 10,
    diameterUnit: 'inch',
    pitch: 4.5,
    pitchUnit: 'inch',
    blades: 2,
    tConst: 0.109,
    pConst: 0.053,
    gearRatio: 1,
    propWeightG: 14,
  },
}
